### ISSUE TITLE
ERROR: module declares its path as: github.com/cucumber/godog but was required as: github.com/DATA-DOG/godog

### ISSUE THREAD

**Issue by Apologiz** [nelkinda/health-go#1]
Hi! I came across an error due to updating the path of the dependent library.

```
go: my_package imports
        github.com/nelkinda/health-go tested by
        github.com/nelkinda/health-go.test imports
        github.com/christianhujer/assert tested by
        github.com/christianhujer/assert.test imports
        github.com/DATA-DOG/godog: github.com/DATA-DOG/godog@v0.9.0: parsing go.mod:
        module declares its path as: github.com/cucumber/godog
                but was required as: github.com/DATA-DOG/godog
```
I recommend changing
from: **github.com/christianhujer/assert**
to: **github.com/stretchr/testify/assert**
Thanks!

**Comment by christianhujer** [comment]
Thank you for reporting this.

1. I have fixed the dependency on `godog` to its new location in cucumber instead of DATA-DOG.
2. I have released `christianhujer/assert` as a module. (I will also move it to `nelkinda/assert-go` later, but that's a different story.)
3. I have released `nelkinda/http-go` as a module.
4. I have released `nelkinda/health-go` as a module.

Please update your dependency to health-go v0.0.1 and let me know if you encounter any further problems.

I have not replaced `christianhujer/assert` with `testify/assert`. Last time I looked at `testify`, it wasn't nice and really horrible to use with `godog`. But I've seen it's come a long way and have even seen that people now found better ways to integrate it with `godog`. So, maybe I will replace it and abandon my own `assert` library. But I need to do some research on my own first.

Also, sorry for the delay in fixing this, I must have missed the notification.
